---
- name: Verify stacks directory exists (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  file:
    path: "/home/{{ansible_user}}/stacks"
    state: directory

- name: Verify prometheus directory exists (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  file:
    path: "/home/{{ansible_user}}/stacks/prometheus"
    state: directory

- name: Create docker-compose stack file for cluster monitor(on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  template:
    src: cluster-monitoring.j2
    dest: /home/{{ansible_user}}/stacks/cluster-monitoring-stack.yml
    mode: 0775

- name: Copy Prometheus rules with owner and permissions
  when: inventory_hostname == groups['swarm_managers'][0]
  ansible.builtin.copy:
    src: ./rules
    dest: /home/{{ansible_user}}/stacks/prometheus
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0644'

- name: Deploy cluster monitoring stack from a compose file (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  docker_stack:
    state: present
    name: cluster_monitoring
    compose:
      - /home/{{ansible_user}}/stacks/cluster-monitoring-stack.yml
  tags: ["monitor"]