---
- name: Verify stacks directory exists. (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["dashy"]
  file:
    path: "/home/{{ansible_user}}/stacks"
    state: directory

- name: Verify stacks directory exists. (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["frontends"]
  file:
    path: "/home/{{ansible_user}}/stacks/frontends"
    state: directory

- name: Verify dashy directory exists. (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["frontends"]
  file:
    path: "/home/{{ansible_user}}/stacks/frontends/dashy"
    state: directory

- name: Check that the conf.yml exists
  become: yes
  stat:
    path: /home/{{ansible_user}}/stacks/frontends/dashy/conf.yml
  register: stat_result

- name: Create the dashy conf file, if it doesnt exist already
  become: yes
  file:
    path: /home/{{ansible_user}}/stacks/frontends/dashy/conf.yml
    state: touch
  when: not stat_result.stat.exists

- name: Create docker-compose stack file for Frontend web ui's (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["frontends"]
  template:
    src: frontend-webui-stack.j2
    dest: /home/{{ansible_user}}/stacks/frontends/webui-stack.yml
    mode: 0775

- name: Deploy frontend web ui's stack from a compose file (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["frontends", "docker-compose"]
  docker_stack:
    state: present
    name: frontends
    compose:
      - /home/{{ansible_user}}/stacks/frontends/webui-stack.yml