---
- name: Check if Swarm has already been initialized
  shell: docker node ls
  tags: ["docker"]
  register: swarm_status
  ignore_errors: true

- name: Add Docker node to existing Swarm as manager
  tags: ["docker"]
  shell: docker swarm join --token {{hostvars[groups['swarm_managers'][0]]['manager_token']['stdout']}} {{groups['swarm_managers'][0]}}:2377
  when: swarm_status.rc != 0 and inventory_hostname != groups['swarm_managers'][0]
